name: Vercel Deployment

on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Allow unsecure commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - uses: ngduc/vercel-deploy-action@master
        with:
          vercel-cli: vercel
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-token: ${{ secrets.VERCEL_TOKEN }}
          vercel-org-id: ${{ secrets.VERCEL_ORG_ID }}
          vercel-project-id: ${{ secrets.VERCEL_PROJECT_ID_STATIC }}
          working-directory: ./ #Your Working Directory, Optional
            
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
