name: Vercel Deployment

on:
  push:
    branches:
      - master  # Adjust this to your main branch name

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
        
      - name: Allow unsecure commands
        run: echo "ACTIONS_ALLOW_UNSECURE_COMMANDS=true" >> $GITHUB_ENV

      - name: Deploy to Vercel Action
        uses: BetaHuhn/deploy-to-vercel-action@v1.9.12    
        with:
          VERCEL_TOKEN: fhnq4sKG7Jv1ghA6tKg0W94z
          GITHUB_TOKEN: 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
          VERCEL_ORG_ID: UKcP3gyAufa0VYg2PqFcdq8l
          VERCEL_PROJECT_ID: prj_A5Ub2Tq2T7DvhbT5o3spSeFOUDVW 
          WORKING_DIRECTORY: ./ #Your Working Directory, Optional
          ALIAS_DOMAINS: | #Optional
            staging.angular.vercel-action.amond.dev
            pr-{{PR_NUMBER}}.angular.vercel-action.amond.dev
            
      - name: preview-url
        run: |
          echo ${{ steps.vercel-action.outputs.preview-url }}
